export const SUPABASE_URL = "HIER_DEINE_SUPABASE_URL";
export const SUPABASE_PUBLISHABLE_KEY = "HIER_DEINEN_SUPABASE_KEY_EINTRAGEN";
export const IS_CONFIGURED = SUPABASE_URL.startsWith("https://") && !SUPABASE_PUBLISHABLE_KEY.includes("HIER_DEINEN");
