import { supabase, compressImage, mapDefaults } from "./app.js";
import { IS_CONFIGURED, SUPABASE_PUBLISHABLE_KEY } from "./config.js";
const map=L.map("map").setView([mapDefaults.ORT_LAT,mapDefaults.ORT_LNG],mapDefaults.START_ZOOM);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"&copy; OpenStreetMap-Mitwirkende"}).addTo(map);let selectedMarker=null;
function setLocation(lat,lng,label){document.querySelector("#lat").value=lat;document.querySelector("#lng").value=lng;if(selectedMarker)selectedMarker.remove();selectedMarker=L.marker([lat,lng]).addTo(map).bindPopup(label).openPopup()}
map.on("click",e=>setLocation(e.latlng.lat,e.latlng.lng,"Ausgewählter Standort"));
document.querySelector("#useGps")?.addEventListener("click",()=>{const status=document.querySelector("#status");if(!navigator.geolocation){status.textContent="GPS wird nicht unterstützt.";return}status.textContent="Standort wird ermittelt ...";navigator.geolocation.getCurrentPosition(pos=>{setLocation(pos.coords.latitude,pos.coords.longitude,"Aktueller Standort");map.setView([pos.coords.latitude,pos.coords.longitude],17);status.textContent="Standort übernommen."},()=>status.textContent="Standort konnte nicht ermittelt werden.")});
document.querySelector("#reportForm")?.addEventListener("submit",async event=>{event.preventDefault();const status=document.querySelector("#status"),lat=Number(document.querySelector("#lat").value),lng=Number(document.querySelector("#lng").value);if(!lat||!lng){status.textContent="Bitte Standort per Karte oder GPS auswählen.";return}if(!IS_CONFIGURED||SUPABASE_PUBLISHABLE_KEY.includes("HIER_DEINEN")){status.textContent="Publishable Key fehlt noch in js/config.js.";return}status.textContent="Meldung wird gespeichert ...";const publicId=crypto.randomUUID();let photoPath=null;try{const file=document.querySelector("#photo").files[0];if(file){status.textContent="Foto wird verkleinert und hochgeladen ...";const compressed=await compressImage(file,1400,.72);photoPath=`${publicId}.jpg`;const{error:uploadError}=await supabase.storage.from("report-photos").upload(photoPath,compressed,{contentType:"image/jpeg",upsert:false});if(uploadError)throw uploadError}const payload={public_id:publicId,address:document.querySelector("#address").value.trim(),severity:Number(document.querySelector("#severity").value),since:document.querySelector("#since").value,time_of_day:document.querySelector("#time_of_day").value,note:document.querySelector("#note").value.trim(),contact_private:document.querySelector("#contact").value.trim(),lat,lng,photo_path:photoPath,status:"pending",visible:false,client_timestamp:new Date().toISOString()};const{error}=await supabase.from("reports").insert(payload);if(error)throw error;status.textContent=`Danke! Meldung ${publicId.slice(0,8)} wurde eingereicht und wird geprüft.`;event.target.reset();if(selectedMarker){selectedMarker.remove();selectedMarker=null}}catch(error){console.error(error);status.textContent="Fehler beim Speichern. Bitte Supabase-Tabellen/Storage/Richtlinien prüfen."}});
<label>Straße / Bereich
  <select name="street" id="streetSelect" required>
    <option value="">Bitte auswählen</option>
    <option value="Bergstraße" data-lat="51.763" data-lng="7.895">Bergstraße</option>
    <option value="Dolberger Straße" data-lat="51.760" data-lng="7.900">Dolberger Straße</option>
    <option value="Oststraße" data-lat="51.765" data-lng="7.902">Oststraße</option>
  </select>
</label>
